# Generated by Django 4.0.10 on 2023-08-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachDoan',
            fields=[
                ('ma_doan', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ten_coquan', models.CharField(max_length=40)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('sdt', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_chi', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'khach_doan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_kh', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cmnd', models.CharField(blank=True, max_length=12, null=True)),
                ('ho_ten', models.CharField(max_length=60)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('sdt', models.CharField(blank=True, max_length=10, null=True)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('dia_chi', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'khach_hang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nv', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cmnd', models.CharField(max_length=12, unique=True)),
                ('ho_ten', models.CharField(max_length=60)),
                ('dia_chi', models.CharField(blank=True, max_length=100, null=True)),
                ('gioi_tinh', models.CharField(blank=True, max_length=1, null=True)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('cong_viec', models.CharField(blank=True, max_length=2, null=True)),
                ('vi_tri', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'nhan_vien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phieudk',
            fields=[
                ('ma_phieu', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ngay_dangky', models.DateField()),
                ('ghichu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phieudk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KhackDoanLe',
            fields=[
                ('ma_doan', models.OneToOneField(db_column='ma_doan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.khachdoan')),
            ],
            options={
                'db_table': 'khack_doan_le',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KyNang',
            fields=[
                ('ma_nv', models.OneToOneField(db_column='ma_nv', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.nhanvien')),
                ('ky_nang', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ky_nang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NgoaiNgu',
            fields=[
                ('ma_nv', models.OneToOneField(db_column='ma_nv', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.nhanvien')),
                ('ngoai_ngu', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ngoai_ngu',
                'managed': False,
            },
        ),
    ]
