# Generated by Django 4.0.10 on 2023-08-04 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiNhanh',
            fields=[
                ('ma_cn', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ten_cn', models.CharField(max_length=40, unique=True)),
                ('khu_vuc', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('fax', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'chi_nhanh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiemDulich',
            fields=[
                ('ma_diem', models.AutoField(primary_key=True, serialize=False)),
                ('ten_diem', models.CharField(max_length=30)),
                ('dia_chi', models.CharField(max_length=100)),
                ('phuong_xa', models.CharField(max_length=20)),
                ('quan_huyen', models.CharField(max_length=20)),
                ('tinh', models.CharField(max_length=20)),
                ('anh1', models.TextField(blank=True, null=True)),
                ('anh2', models.TextField(blank=True, null=True)),
                ('anh3', models.TextField(blank=True, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'diem_dulich',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonviCungcap',
            fields=[
                ('ma_donvi', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ten_donvi', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('sdt_dvcc', models.CharField(blank=True, max_length=10, null=True)),
                ('ten_nguoidaidien', models.CharField(blank=True, max_length=60, null=True)),
                ('sdt_nguoidaidien', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_chi', models.CharField(max_length=100)),
                ('phuong_xa', models.CharField(max_length=20)),
                ('quan_huyen', models.CharField(max_length=20)),
                ('tinh', models.CharField(max_length=20)),
                ('anh1', models.TextField(blank=True, null=True)),
                ('anh2', models.TextField(blank=True, null=True)),
                ('anh3', models.TextField(blank=True, null=True)),
                ('anh4', models.TextField(blank=True, null=True)),
                ('anh5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donvi_cungcap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('ma_tour', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('ten_tour', models.CharField(max_length=40, unique=True)),
                ('anh', models.TextField(blank=True, max_length=200, null=True)),
                ('ngay_batdau', models.DateField()),
                ('sokhach_toida', models.IntegerField()),
                ('giave_kl_nguoilon', models.IntegerField()),
                ('giave_kl_treem', models.IntegerField()),
                ('giave_kd_nguoilon', models.IntegerField()),
                ('giave_kd_treem', models.IntegerField()),
                ('sokhach_toithieu', models.IntegerField()),
                ('sokhachdoan_toithieu', models.IntegerField(blank=True, null=True)),
                ('so_dem', models.IntegerField()),
                ('so_ngay', models.IntegerField()),
            ],
            options={
                'db_table': 'tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chuyendi',
            fields=[
                ('ma_tour', models.OneToOneField(db_column='ma_tour', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tour.tour')),
                ('ngay_khoihanh', models.DateField()),
                ('ngay_ketthuc', models.DateField(blank=True, null=True)),
                ('tonggia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chuyendi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DvccDvlq',
            fields=[
                ('ma_tour', models.OneToOneField(db_column='ma_tour', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tour.tour')),
            ],
            options={
                'db_table': 'dvcc_dvlq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lichtrinhtour',
            fields=[
                ('ma_tour', models.OneToOneField(db_column='ma_tour', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tour.tour')),
                ('stt_ngay', models.IntegerField()),
            ],
            options={
                'db_table': 'lichtrinhtour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NgaykhoihanhTourdai',
            fields=[
                ('ma_tour', models.OneToOneField(db_column='ma_tour', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tour.tour')),
                ('ngay', models.IntegerField()),
            ],
            options={
                'db_table': 'ngaykhoihanh_tourdai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoDienThoaiChiNhanh',
            fields=[
                ('ma_cn', models.OneToOneField(db_column='ma_cn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tour.chinhanh')),
                ('sdt_cn', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'so_dien_thoai_chi_nhanh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diemxp', models.CharField(choices=[('AG', 'An Giang'), ('BRVT', 'Ba Ria - Vung Tau'), ('BL', 'Bac Lieu'), ('BK', 'Bac Kan'), ('BG', 'Bac Giang'), ('BN', 'Bac Ninh'), ('BT', 'Ben Tre'), ('BD', 'Binh Duong'), ('BĐ', 'Binh Dinh'), ('BP', 'Binh Phuoc'), ('BTH', 'Binh Thuan'), ('CM', 'Ca Mau'), ('CB', 'Cao Bang'), ('CT', 'Can Tho'), ('DNG', 'Da Nang'), ('DL', 'Dak Lak'), ('DKN', 'Dak Nong'), ('DB', 'Dien Bien'), ('DN', 'Dong Nai'), ('DT', 'Dong Thap'), ('GL', 'Gia Lai'), ('HAUG', 'Ha Giang'), ('HNAM', 'Ha Nam'), ('HNOI', 'Ha Noi'), ('HT', 'Ha Tinh'), ('HD', 'Hai Duong'), ('HP', 'Hai Phong'), ('HB', 'Hoa Binh'), ('HG', 'Hau Giang'), ('HY', 'Hung Yen'), ('HCMC', 'Ho Chi Minh City'), ('KH', 'Khanh Hoa'), ('KG', 'Kien Giang'), ('KT', 'Kon Tum'), ('LCH', 'Lai Chau'), ('LD', 'Lam Dong'), ('LS', 'Lang Son'), ('LCAI', 'Lao Cai'), ('LA', 'Long An'), ('ND', 'Nam Dinh'), ('NA', 'Nghe An'), ('NB', 'Ninh Binh'), ('NT', 'Ninh Thuan'), ('PT', 'Phu Tho'), ('PY', 'Phu Yen'), ('QB', 'Quang Binh'), ('QNM', 'Quang Nam'), ('QNG', 'Quang Ngai'), ('QNI', 'Quang Ninh'), ('QT', 'Quang Tri'), ('ST', 'Soc Trang'), ('SL', 'Son La'), ('TNI', 'Tay Ninh'), ('TB', 'Thai Binh'), ('TN', 'Thai Nguyen'), ('TH', 'Thanh Hoa'), ('TTH', 'Thua Thien Hue')], default='HNOI', max_length=10)),
                ('diemden', models.CharField(choices=[('AG', 'An Giang'), ('BRVT', 'Ba Ria - Vung Tau'), ('BL', 'Bac Lieu'), ('BK', 'Bac Kan'), ('BG', 'Bac Giang'), ('BN', 'Bac Ninh'), ('BT', 'Ben Tre'), ('BD', 'Binh Duong'), ('BĐ', 'Binh Dinh'), ('BP', 'Binh Phuoc'), ('BTH', 'Binh Thuan'), ('CM', 'Ca Mau'), ('CB', 'Cao Bang'), ('CT', 'Can Tho'), ('DNG', 'Da Nang'), ('DL', 'Dak Lak'), ('DKN', 'Dak Nong'), ('DB', 'Dien Bien'), ('DN', 'Dong Nai'), ('DT', 'Dong Thap'), ('GL', 'Gia Lai'), ('HAUG', 'Ha Giang'), ('HNAM', 'Ha Nam'), ('HNOI', 'Ha Noi'), ('HT', 'Ha Tinh'), ('HD', 'Hai Duong'), ('HP', 'Hai Phong'), ('HB', 'Hoa Binh'), ('HG', 'Hau Giang'), ('HY', 'Hung Yen'), ('HCMC', 'Ho Chi Minh City'), ('KH', 'Khanh Hoa'), ('KG', 'Kien Giang'), ('KT', 'Kon Tum'), ('LCH', 'Lai Chau'), ('LD', 'Lam Dong'), ('LS', 'Lang Son'), ('LCAI', 'Lao Cai'), ('LA', 'Long An'), ('ND', 'Nam Dinh'), ('NA', 'Nghe An'), ('NB', 'Ninh Binh'), ('NT', 'Ninh Thuan'), ('PT', 'Phu Tho'), ('PY', 'Phu Yen'), ('QB', 'Quang Binh'), ('QNM', 'Quang Nam'), ('QNG', 'Quang Ngai'), ('QNI', 'Quang Ninh'), ('QT', 'Quang Tri'), ('ST', 'Soc Trang'), ('SL', 'Son La'), ('TNI', 'Tay Ninh'), ('TB', 'Thai Binh'), ('TN', 'Thai Nguyen'), ('TH', 'Thanh Hoa'), ('TTH', 'Thua Thien Hue')], default='HCMC', max_length=10)),
                ('category', models.CharField(choices=[('TN', 'Tour trong ngày'), ('DN', 'Tour dài ngày')], default='TN', max_length=9)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('AVAIL', 'Available'), ('HLD', 'On Hold')], default='AVAIL', max_length=9)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='DiadiemThamquan',
            fields=[
                ('ma_tour', models.OneToOneField(db_column='ma_tour', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='diadiem_thamquan_ma_tour', serialize=False, to='tour.lichtrinhtour')),
                ('thoigian_batdau', models.DateField(blank=True, null=True)),
                ('thoigian_ketthuc', models.DateField(blank=True, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diadiem_thamquan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HanhdongLichtrinhtour',
            fields=[
                ('ma_tour', models.OneToOneField(db_column='ma_tour', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='hanhdong_lichtrinhtour_ma_tour', serialize=False, to='tour.lichtrinhtour')),
                ('loai_hanhdong', models.IntegerField()),
                ('thoigian_batdau', models.DateField(blank=True, null=True)),
                ('thoigian_ketthuc', models.DateField(blank=True, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hanhdong_lichtrinhtour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HdvChuyendi',
            fields=[
                ('ma_tour', models.OneToOneField(db_column='ma_tour', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='hdvchuyendi_ma_tour', serialize=False, to='tour.chuyendi')),
            ],
            options={
                'db_table': 'hdv_chuyendi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LichtrinhChuyen',
            fields=[
                ('ma_tour', models.OneToOneField(db_column='ma_tour', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tour.chuyendi')),
                ('stt_ngay', models.IntegerField()),
            ],
            options={
                'db_table': 'lichtrinh_chuyen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DvccDvchuyendi',
            fields=[
                ('ma_tour', models.OneToOneField(db_column='ma_tour', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tour.lichtrinhchuyen')),
                ('loai', models.IntegerField()),
            ],
            options={
                'db_table': 'dvcc_dvchuyendi',
                'managed': False,
            },
        ),
    ]
