# Generated by Django 4.0.10 on 2023-07-31 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('matour', models.AutoField(db_column='MaTour', primary_key=True, serialize=False)),
                ('tentour', models.CharField(blank=True, db_column='TenTour', max_length=255, null=True)),
                ('anh', models.CharField(blank=True, db_column='Anh', max_length=255, null=True)),
                ('ngaybatdau', models.DateField(blank=True, db_column='NgayBatDau', null=True)),
                ('sokhachtourtoithieu', models.IntegerField(blank=True, db_column='SoKhachTourToiThieu', null=True)),
                ('sokhachtourtoida', models.IntegerField(blank=True, db_column='SoKhachTourToiDa', null=True)),
                ('giavelenguoilon', models.FloatField(blank=True, db_column='GiaVeLeNguoiLon', null=True)),
                ('giaveletreem', models.FloatField(blank=True, db_column='GiaVeLeTreEm', null=True)),
                ('giavedoannguoilon', models.FloatField(blank=True, db_column='GiaVeDoanNguoiLon', null=True)),
                ('giavedoantreem', models.FloatField(blank=True, db_column='GiaVeDoanTreEm', null=True)),
                ('sokhachdoantoithieu', models.IntegerField(blank=True, db_column='SoKhachDoanToiThieu', null=True)),
                ('sodem', models.IntegerField(db_column='SoDem')),
                ('songay', models.IntegerField(db_column='SoNgay')),
                ('machinhanh', models.IntegerField(blank=True, db_column='MaChiNhanh', null=True)),
            ],
            options={
                'db_table': 'tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tours', serialize=False, to='tour.tour')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='tour_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(choices=[('AG', 'An Giang'), ('BRVT', 'Ba Ria - Vung Tau'), ('BL', 'Bac Lieu'), ('BK', 'Bac Kan'), ('BG', 'Bac Giang'), ('BN', 'Bac Ninh'), ('BT', 'Ben Tre'), ('BD', 'Binh Duong'), ('BĐ', 'Binh Dinh'), ('BP', 'Binh Phuoc'), ('BTH', 'Binh Thuan'), ('CM', 'Ca Mau'), ('CB', 'Cao Bang'), ('CT', 'Can Tho'), ('DNG', 'Da Nang'), ('DL', 'Dak Lak'), ('DKN', 'Dak Nong'), ('DB', 'Dien Bien'), ('DN', 'Dong Nai'), ('DT', 'Dong Thap'), ('GL', 'Gia Lai'), ('HAUG', 'Ha Giang'), ('HNAM', 'Ha Nam'), ('HNOI', 'Ha Noi'), ('HT', 'Ha Tinh'), ('HD', 'Hai Duong'), ('HP', 'Hai Phong'), ('HB', 'Hoa Binh'), ('HG', 'Hau Giang'), ('HY', 'Hung Yen'), ('HCMC', 'Ho Chi Minh City'), ('KH', 'Khanh Hoa'), ('KG', 'Kien Giang'), ('KT', 'Kon Tum'), ('LCH', 'Lai Chau'), ('LD', 'Lam Dong'), ('LS', 'Lang Son'), ('LCAI', 'Lao Cai'), ('LA', 'Long An'), ('ND', 'Nam Dinh'), ('NA', 'Nghe An'), ('NB', 'Ninh Binh'), ('NT', 'Ninh Thuan'), ('PT', 'Phu Tho'), ('PY', 'Phu Yen'), ('QB', 'Quang Binh'), ('QNM', 'Quang Nam'), ('QNG', 'Quang Ngai'), ('QNI', 'Quang Ninh'), ('QT', 'Quang Tri'), ('ST', 'Soc Trang'), ('SL', 'Son La'), ('TNI', 'Tay Ninh'), ('TB', 'Thai Binh'), ('TN', 'Thai Nguyen'), ('TH', 'Thanh Hoa'), ('TTH', 'Thua Thien Hue')], default='HNOI', max_length=10)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('AVAIL', 'Available'), ('HLD', 'On Hold')], default='PEN', max_length=9)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tour.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
