# Generated by Django 4.0.10 on 2023-07-27 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('MaTour', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('Anh', models.CharField(max_length=255)),
                ('NgayBatDau', models.DateField(blank=True, null=True)),
                ('SoKhachTourToiThieu', models.IntegerField()),
                ('SoKhachTourToiDa', models.IntegerField()),
                ('GiaVeLeNguoiLon', models.FloatField()),
                ('GiaVeLeTreEm', models.FloatField()),
                ('GiaVeDoanNguoiLon', models.FloatField()),
                ('GiaVeDoanTreEm', models.FloatField()),
                ('SoKhachDoanToiThieu', models.IntegerField(blank=True, null=True)),
                ('SoDem', models.IntegerField(blank=True, null=True)),
                ('SoNgay', models.IntegerField(blank=True, null=True)),
                ('MaChiNhanh', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='tour_images')),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tour.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tour',
                'managed': True,
            },
        ),
    ]
